# Generated by Django 5.1.2 on 2024-10-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser_last_name_historicaluser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('administrativo', 'Admin'), ('gerente', 'Gerente'), ('contador', 'Contador'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrativo', 'Admin'), ('gerente', 'Gerente'), ('contador', 'Contador'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
    ]
