# Generated by Django 5.1.2 on 2024-11-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=60, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=10, verbose_name='Cédula')),
                ('address_home', models.CharField(max_length=100, verbose_name='Dirección Domiciliaria')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=10, verbose_name='Número de Teléfono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
